#
# FloPi
#
# Floppy Music for Raspberry Pi
#
# (c) 2015 Bernd Busse
#

VERSION = 0.1.0
MAKE    = /usr/bin/make
CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -DVERSION=\"$(VERSION)\"
LDFLAGS = -lwiringPi -lasound 

%.o: %.c
	$(CC) $(CFLAGS) -c $<

